controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rebel_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

rebel_arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    gains:
      joint1: { p: 100.0, d: 1.0, i: 0.02, i_clamp: 1.0, ff_velocity_scale: 1.0 }
      joint2: { p: 100.0, d: 1.0, i: 0.02, i_clamp: 1.0, ff_velocity_scale: 1.0 }
      joint3: { p: 100.0, d: 1.0, i: 0.02, i_clamp: 1.0, ff_velocity_scale: 1.0 }
      joint4: { p: 100.0, d: 1.0, i: 0.02, i_clamp: 1.0, ff_velocity_scale: 1.0 }
      joint5: { p: 100.0, d: 1.0, i: 0.02, i_clamp: 1.0, ff_velocity_scale: 1.0 }
      joint6: { p: 100.0, d: 1.0, i: 0.02, i_clamp: 1.0, ff_velocity_scale: 1.0 }